container-name-run : "bp3driventestwebreact-express-run"
container-name-tools : "bp3driventestwebreact-express-tools"

host-path-run : "."
host-path-tools : "."

container-path-run : "/app"
container-path-tools : "/app"

container-port-map : "8080:8080"
container-port-map-debug : "5858:5858"

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"

image-name-run : "bp3driventestwebreact-express-run"
image-name-tools : "bp3driventestwebreact-express-tools"

build-cmd-run : "npm install --production --unsafe-perm"
test-cmd : "npm run test"
build-cmd-debug : "npm install --unsafe-perm"

run-cmd : ""
debug-cmd : "npm run debug"
stop-cmd : "npm stop"

version : "0.0.3"
ibm-generated-id : "6b47c42a-1bff-42e1-b312-77a0474cbe24"
credentials-filepath : "server/localdev-config.json, vcap-local.js, credentials.json"